name: APK Uret

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Projeyi Hazirla ve Derle
        run: |
          # Temiz bir Flutter projesi oluştur
          flutter create --org com.afitashali --project-name afitashali app_build
          
          # Bizim yazdığımız kod dosyasını içine kopyala
          cp lib/main.dart app_build/lib/main.dart
          
          # Proje dizinine geç ve derle
          cd app_build
          flutter pub get
          flutter build apk --release

      - name: APK Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Afitashali-APK
          path: app_build/build/app/outputs/flutter-apk/app-release.apk
